/* Generated By:JavaCC: Do not edit this line. AdderConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AdderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int EQUAL = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int OPEN_PAR = 10;
  /** RegularExpression Id. */
  int CLOSE_PAR = 11;
  /** RegularExpression Id. */
  int CHARACTER = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int END = 14;
  /** RegularExpression Id. */
  int STRING = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<EOL>",
    "\"and\"",
    "\"or\"",
    "\"=\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "<CHARACTER>",
    "\":\"",
    "\";\"",
    "<STRING>",
  };

}
