/* Generated By:JavaCC: Do not edit this line. ParseConditionConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParseConditionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int EQUAL = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int GREATER = 10;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 11;
  /** RegularExpression Id. */
  int LESS = 12;
  /** RegularExpression Id. */
  int LESS_EQUAL = 13;
  /** RegularExpression Id. */
  int OPEN_PAR = 14;
  /** RegularExpression Id. */
  int CLOSE_PAR = 15;
  /** RegularExpression Id. */
  int CHARACTER = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int END = 18;
  /** RegularExpression Id. */
  int STRING = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<EOL>",
    "\"and\"",
    "\"or\"",
    "\"=\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"(\"",
    "\")\"",
    "<CHARACTER>",
    "\"%\"",
    "\";\"",
    "<STRING>",
  };

}
